flag SignerInformationEntity for deletion
eu-digital-green-certificates/dgc-gateway pull request #166
Opened 2022-03-21 08:48 UTC by bergmann-dierk

2022-03-21 09:03 UTC, f11h requested changes
I would suppose to keep the thumbprint of a certificates - otherwise the MS wouldn't know which certificates was deleted.

2022-03-21 09:03 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java
> +    @Column(name = "thumbprint", length = 64, unique = true)
```suggestion
    @Column(name = "thumbprint", nullable = false, length = 64, unique = true)
```

2022-03-21 09:03 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
> +        signerInformationEntity.setThumbprint(null);
```suggestion
```

2022-03-21 09:03 UTC, f11h commented on src/main/resources/db/changelog/alter-signer-information-for-deletion.xml
> +        <dropNotNullConstraint tableName="signer_information" columnName="thumbprint"/>
```suggestion
```

2022-03-23 06:31 UTC, bergmann-dierk commented
> I would suppose to keep the thumbprint of a certificates - otherwise the MS wouldn't know which certificates was deleted.

Keeping raw_data and Thumbprint but returning raw_data as null.
raw_data is needed to calculate kid

2022-03-23 08:04 UTC, merged