Feature/dsc delta download extension
eu-digital-green-certificates/dgc-gateway pull request #169
Opened 2022-03-21 13:56 UTC by hhmu

feature implemented without deletion, which is in #166

2022-03-23 14:43 UTC, f11h requested changes

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +    private static final String IF_MODIFIED_SINCE_HEADER = "If-Modified-Since";
```suggestion
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +import org.springframework.http.HttpStatus;
```suggestion
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +                name = "If-Modified-Since",
```suggestion
                name = HttpHeaders.IF_MODIFIED_SINCE,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        @RequestHeader(value = IF_MODIFIED_SINCE_HEADER, required = false) String ifModifiedSince,
```suggestion
        @RequestHeader(value = HttpHeaders.IF_MODIFIED_SINCE, required = false) ZonedDateTime ifModifiedSince,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        }
```suggestion
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        }
```suggestion
        if (isPaginationRequired(page,size)) {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(ifModifiedSince, page, size));
        } else {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(ifModifiedSince, null, null));
        }
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +                name = "If-Modified-Since",
```suggestion
                name = HttpHeaders.IF_MODIFIED_SINCE,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        @RequestHeader(value = IF_MODIFIED_SINCE_HEADER, required = false) String ifModifiedSince,
```suggestion
        @RequestHeader(value = HttpHeaders.IF_MODIFIED_SINCE, required = false) ZonedDateTime ifModifiedSince,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        }
```suggestion
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        }
```suggestion
        if (isPaginationRequired(page,size)) {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(mappedType, ifModifiedSince, page, size));
        } else {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(mappedType, ifModifiedSince, null, null));
        }
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +                name = "If-Modified-Since",
```suggestion
                name = HttpHeaders.IF_MODIFIED_SINCE,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        @RequestHeader(value = IF_MODIFIED_SINCE_HEADER, required = false) String ifModifiedSince,
```suggestion
        @RequestHeader(value = HttpHeaders.IF_MODIFIED_SINCE, required = false) ZonedDateTime ifModifiedSince,
```

2022-03-23 14:43 UTC, f11h commented on src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
> +        }
```suggestion
        if (isPaginationRequired(page,size)) {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(mappedType, countryCode, ifModifiedSince, page, size));
        } else {
            trustList = trustListMapper.trustListToTrustListDto(
                trustListService.getTrustList(mappedType, countryCode, ifModifiedSince, null, null));
        }
```

2022-03-23 21:09 UTC, ascheibal approved these changes

2022-03-23 21:09 UTC, ascheibal approved these changes

2022-03-23 21:13 UTC, ascheibal approved these changes

2022-03-24 07:45 UTC, f11h commented on src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java
> +    private static final String nowMinusOneHourStr = formatter.format(nowMinusOneHour);
This has to be ISO 8601 date format

2022-03-24 08:04 UTC, f11h approved these changes

2022-03-24 08:04 UTC, merged